
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tradeprohub
      POSTGRES_USER: tradepro
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: