# Generated by Django 4.2.7 on 2025-07-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galleryimage",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="availability_schedule",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="available_immediately",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="business_logo",
            field=models.ImageField(blank=True, null=True, upload_to="business_logos/"),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="certifications",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="minimum_charge",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly Rate"),
                    ("quoted", "Quoted Projects"),
                    ("both", "Both Hourly and Quoted"),
                ],
                default="hourly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="quote_packages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="service_area_type",
            field=models.CharField(
                choices=[
                    ("radius", "Radius from location"),
                    ("town", "Entire town/city"),
                    ("county", "Entire county"),
                    ("state", "Entire state"),
                    ("custom_draw", "Custom drawn area"),
                ],
                default="radius",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="willing_to_travel_outside",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="service_radius",
            field=models.IntegerField(default=25),
        ),
        migrations.CreateModel(
            name="ServicePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_packages",
                        to="profiles.businessprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["price"],
            },
        ),
    ]
